site_name: Cluster.dev
# Page tree
repo_name: 'shalb/cluster.dev'
repo_url: 'https://github.com/shalb/cluster.dev'
site_url: 'https://docs.cluster.dev'


nav:
  - Introduction:
    - Overview:
      - What Is Cluster.dev?: index.md
      - How Does It Work?: how-does-cdev-work.md
    - Getting Started:
      - Prerequisites: get-started-prerequisites.md
      - Install: get-started-install.md
      - Install From Sources: get-started-install-from-sources.md
      - Create New Project: get-started-create-project.md
    - Examples:
      - AWS-EKS: examples-aws-eks.md
      - DO-K8s: examples-do-k8s.md
      - Modify AWS-EKS: examples-modify-aws-eks.md
      - Develop Stack Template: examples-develop-stack-template.md
    - Cluster.dev vs. Others:
      - Cluster.dev vs. Terraform: cdev-vs-terraform.md
      - Cluster.dev vs. Pulumi & Crossplane: cdev-vs-pulumi.md
  - Reference:
    - Structure:
      - Overview: structure-overview.md
      - Project: structure-project.md
      - Stack: structure-stack.md
      - Backend: structure-backend.md
      - Secrets: structure-secrets.md
    - Stack Templates:
      - Overview: stack-templates-overview.md
      - Functions: stack-templates-functions.md
      - Stack Templates List: stack-templates-list.md
    - Units:
      - Overview: units-overview.md
      - Terraform: units-terraform.md
      - Helm: units-helm.md
      - Kubernetes: units-kubernetes.md
      - Printer: units-printer.md
    - CLI Reference:
      - CLI Commands: cli-commands.md
      - CLI Options: cli-options.md
      - Environment variables: env-variables.md
    - How-to Articles:
      - Use Different Terraform versions: howto-tf-versions.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: ' ¶'
theme:
  name: 'material'
  custom_dir: docs/theme-overrides
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mod
  font:
    text: Roboto
    code: Roboto Mono
  logo: '/images/cluster-dev-logo-site.png'
  favicon: 'images/favicon.png'
google_analytics:
  - G-KK8Z11MM4P
  - auto
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/cluster-dev/shared_invite/zt-eg4q6jae-v0~zgrBLYTTXt~CjnjmprA
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shalbcom
    - icon: fontawesome/brands/github
      link: https://github.com/shalb/cluster.dev
