site_name: Cluster.dev
# Page tree
repo_name: 'shalb/cluster.dev'
repo_url: 'https://github.com/shalb/cluster.dev'
site_url: 'https://cluster.dev'


nav:
  - Home:
    - Welcome: index.md
    - How to Use Cdev: how-to-use.md
    - Documentation Structure: documentation-structure.md
  - User Mode:
    - Getting Started: getting-started.md
    - Deploying to AWS: aws-cloud-provider.md
    - Deploying to DigitalOcean: digital-ocean-cloud-provider.md
    - Deploying to GCE: google-cloud-provider.md
    - Deploying to Azure: azure-cloud-provider.md
    - Cdev Install Reference: cdev-installation-reference.md
  - Developer Mode: 
    - Template Development: stack-template-development.md
    - Workflow: template-development-workflow.md
  - Reference:
    - Project Configuration: project-configuration.md
    - CLI Reference:
      - CLI Commands: cli-commands.md
      - CLI Options: cli-options.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: ' ¶'
theme:
  name: 'material'
  custom_dir: docs/theme-overrides
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mod
  font:
    text: Roboto
    code: Roboto Mono
  logo: '/images/cluster-dev-logo-site.png'
  favicon: 'images/favicon.png'
google_analytics:
  - UA-157259461-1
  - auto
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/cluster-dev/shared_invite/zt-eg4q6jae-v0~zgrBLYTTXt~CjnjmprA
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shalbcom
    - icon: fontawesome/brands/github
      link: https://github.com/shalb/cluster.dev
